console.log("Hello Winc Academy");
let eigenNaam = "Alex van Maaren";
console.log(eigenNaam);
let nr1 = 4;
let nr2 = 4;
console.log(nr1 + nr2);
let nr3 = "4";
let nr4 = "4";
console.log(nr3 + nr4);
let nr5 = 8;
let nr6 = 4;
console.log(nr5 + nr6);
console.log(nr5 - nr6);
console.log(nr5 * nr6);
console.log(nr5 / nr6);
console.log(nr5 % nr6);
let leeftijd = 47;
console.log(typeof leeftijd);
let leeftijd2 = "47";
console.log(typeof leeftijd2);
